import React from 'react';
import { motion } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { 
  Brain, Calendar, ExternalLink, Download, 
  Target, Users, Code, Lightbulb, TrendingUp,
  CheckCircle, ArrowRight, AlertTriangle
} from 'lucide-react';

interface BlueprintResultsProps {
  data: {
    analysis: any;
    conversationHistory: any[];
    blueprint: any;
    disclaimer: string;
  };
  onStartOver: () => void;
}

const BlueprintResults: React.FC<BlueprintResultsProps> = ({ data, onStartOver }) => {
  const { analysis, conversationHistory, blueprint, disclaimer } = data;

  const handleScheduleCall = () => {
    window.open('https://calendly.com/krish-mindmaker', '_blank');
  };

  const handleDownloadBlueprint = () => {
    const content = JSON.stringify(blueprint, null, 2);
    const blob = new Blob([content], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${analysis.industry || 'business'}-blueprint.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary/20 via-background to-primary/10 p-6">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-8"
        >
          <div className="flex items-center justify-center gap-3 mb-4">
            <Brain className="w-8 h-8 text-primary" />
            <h1 className="text-3xl font-bold text-foreground">Your Business Blueprint</h1>
          </div>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Generated by Krish's AI Clone based on your strategic consultation
          </p>
        </motion.div>

        {/* AI Disclaimer */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.2 }}
          className="mb-8"
        >
          <Card className="bg-amber-50/80 border-amber-200/50 backdrop-blur-sm">
            <CardContent className="p-6">
              <div className="flex items-start gap-3">
                <AlertTriangle className="w-5 h-5 text-amber-600 mt-1" />
                <div className="flex-1">
                  <h3 className="font-medium text-amber-900 mb-2">AI-Generated Recommendations</h3>
                  <p className="text-sm text-amber-800">{disclaimer}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Main CTA */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.3 }}
          className="mb-8"
        >
          <Card className="bg-gradient-to-r from-primary/10 to-primary-glow/10 border-primary/20 backdrop-blur-sm">
            <CardContent className="p-8 text-center">
              <h2 className="text-2xl font-bold text-foreground mb-4">Ready to Turn This Into Reality?</h2>
              <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
                Schedule a 1-on-1 consultation with the real Krish to refine this blueprint, 
                validate your strategy, and create a detailed implementation roadmap.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button 
                  onClick={handleScheduleCall}
                  className="bg-primary hover:bg-primary/90 text-white px-8 py-3 text-lg"
                >
                  <Calendar className="w-5 h-5 mr-2" />
                  Schedule Call with Krish
                  <ExternalLink className="w-4 h-4 ml-2" />
                </Button>
                <Button 
                  variant="outline" 
                  onClick={handleDownloadBlueprint}
                  className="bg-white/50 border-white/20 hover:bg-white/70"
                >
                  <Download className="w-5 h-5 mr-2" />
                  Download Blueprint
                </Button>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Blueprint Sections */}
        <div className="grid gap-6">
          {/* Executive Summary */}
          {blueprint.executiveSummary && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
            >
              <Card className="bg-white/80 backdrop-blur-sm border-white/20">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Target className="w-5 h-5 text-primary" />
                    Executive Summary
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div>
                    <h4 className="font-medium text-foreground mb-2">Product Vision</h4>
                    <p className="text-muted-foreground">{blueprint.executiveSummary.productVision}</p>
                  </div>
                  <div>
                    <h4 className="font-medium text-foreground mb-2">Target Market</h4>
                    <p className="text-muted-foreground">{blueprint.executiveSummary.targetMarket}</p>
                  </div>
                  <div>
                    <h4 className="font-medium text-foreground mb-2">Value Proposition</h4>
                    <p className="text-muted-foreground">{blueprint.executiveSummary.valueProposition}</p>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Lovable Prompts */}
          {blueprint.lovablePrompts && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
            >
              <Card className="bg-white/80 backdrop-blur-sm border-white/20">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Code className="w-5 h-5 text-primary" />
                    Lovable-Ready Prompts
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {blueprint.lovablePrompts.map((prompt: string, index: number) => (
                    <div key={index} className="p-4 bg-primary/5 rounded-lg border border-primary/10">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge variant="secondary">Prompt {index + 1}</Badge>
                      </div>
                      <p className="text-sm text-muted-foreground whitespace-pre-line">{prompt}</p>
                    </div>
                  ))}
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Technical Specifications */}
          {blueprint.technicalSpecifications && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6 }}
            >
              <Card className="bg-white/80 backdrop-blur-sm border-white/20">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Code className="w-5 h-5 text-primary" />
                    Technical Blueprint
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {blueprint.technicalSpecifications.features && (
                    <div>
                      <h4 className="font-medium text-foreground mb-2">Core Features</h4>
                      <ul className="space-y-1">
                        {blueprint.technicalSpecifications.features.map((feature: string, index: number) => (
                          <li key={index} className="flex items-center gap-2 text-sm text-muted-foreground">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            {feature}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </CardContent>
              </Card>
            </motion.div>
          )}

          {/* Business Strategy */}
          {blueprint.businessStrategy && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.7 }}
            >
              <Card className="bg-white/80 backdrop-blur-sm border-white/20">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <TrendingUp className="w-5 h-5 text-primary" />
                    Business Strategy
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {blueprint.businessStrategy.revenueModel && (
                    <div>
                      <h4 className="font-medium text-foreground mb-2">Revenue Model</h4>
                      <p className="text-muted-foreground">{blueprint.businessStrategy.revenueModel}</p>
                    </div>
                  )}
                  {blueprint.businessStrategy.goToMarket && (
                    <div>
                      <h4 className="font-medium text-foreground mb-2">Go-to-Market Strategy</h4>
                      <p className="text-muted-foreground">{blueprint.businessStrategy.goToMarket}</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </motion.div>
          )}
        </div>

        {/* Conversation Summary */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="mt-8"
        >
          <Card className="bg-white/60 backdrop-blur-sm border-white/20">
            <CardHeader>
              <CardTitle className="text-lg">Your Consultation Journey</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {conversationHistory.map((item, index) => (
                  <div key={index} className="text-sm">
                    <Badge variant="outline" className="mb-1">{item.category}</Badge>
                    <p className="text-muted-foreground font-medium">{item.question}</p>
                    <p className="text-foreground mt-1">{item.answer}</p>
                    {index < conversationHistory.length - 1 && <Separator className="mt-3" />}
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </motion.div>

        {/* Footer Actions */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.9 }}
          className="mt-8 text-center"
        >
          <Button variant="outline" onClick={onStartOver} className="bg-white/50 border-white/20 hover:bg-white/70">
            Start New Consultation
          </Button>
        </motion.div>
      </div>
    </div>
  );
};

export default BlueprintResults;